service: serverless-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  profile: default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
      Resource: '*'
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: '*'
  environment:
    PG_HOST: database-1.cv9gu4mxf0eg.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: postgres
    PG_USERNAME: postgres
    PG_PASSWORD: postgrespostgres

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'